### ISSUE TITLE
Operator deployment error

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#109]
Getting following error when trying to deploy an Operator on a real cluster

Name:https://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true
panic: Get https://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true: dial tcp: lookup github.com on 10.0.0.10:53: server misbehaving

goroutine 1 [running]:
main.locateChartPath(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200b0240, 0x60, 0x0, 0x0, ...)
	/home/devdatta/Code/go/src/github.com/cloud-ark/kubeplus/operator-deployer/install.go:517 +0xea1
main.newInstallCmd(0x18da520, 0xc42083cb40, 0x18ab6a0, 0xc42000e018, 0xc4200b0240, 0x60, 0x0, 0x0, 0x0, 0x0, ...)
	/home/devdatta/Code/go/src/github.com/cloud-ark/kubeplus/operator-deployer/install.go:178 +0x1cc
main.main()
	/home/devdatta/Code/go/src/github.com/cloud-ark/kubeplus/operator-deployer/helm.go:203 +0x9f5

--
Ruling out DNS issue as the error persists even after 
updating /etc/resolve.conf to include
nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by devdattakulkarni** [comment]
The issue was arising because Kubeplus Pods were not able to reach out to the world. Fix was to update the kube-dns configmap. Check 
https://github.com/cloud-ark/kubeplus/issues/108
