### ISSUE TITLE
Concurrent map write error 

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#1123]
Saw following error in crd-hook when requests to create instances was made in quick succession.

`fatal error: concurrent map writes

goroutine 34566 [running]:
runtime.throw({0x1549f3d?, 0xc00110321c?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc001103028 sp=0xc001102ff8 pc=0x433f51
runtime.mapassign_faststr(0xc000d4f236?, 0x3a?, {0xc001345360, 0x4f})
	/usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc001103090 sp=0xc001103028 pc=0x41311c
main.handleCustomAPIs(0xc001082bd0)
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:1161 +0x707 fp=0xc001103470 sp=0xc001103090 pc=0x1292b07
main.(*WebhookServer).mutate(0x1738940?, 0xc001082bd0, {0xc000374070, 0x6})
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:172 +0x827 fp=0xc001103828 sp=0xc001103470 pc=0x128a267
main.(*WebhookServer).serve(0x0?, {0x1749ff0, 0xc0000a4d20}, 0xc000d62800)
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:1526 +0x44f fp=0xc0011039f0 sp=0xc001103828 pc=0x1293aaf
`

**Comment by devdattakulkarni** [comment]
Closing this for now as this error has not happened in further testing. We can reopen this issue if we see the error again.
