### ISSUE TITLE
Failed to list *v1.Postgres: the server could not find the requested resource (get postgreses.postgrescontroller.kubeplus)

### ISSUE THREAD

**Issue by chrisduong** [cloud-ark/kubeplus#13]
Hi,

I tried your Custom Resource Postgres. But it failed

```
E0424 11:08:56.640812   44329 reflector.go:205] github.com/cloud-ark/kubeplus/postgres-crd/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1.Postgres: the server could not find the requested resource (get postgreses.postgrescontroller.kubeplus)
E0424 11:08:57.645547   44329 reflector.go:205] github.com/cloud-ark/kubeplus/postgres-crd/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1.Postgres: the server could not find the requested resource (get postgreses.postgrescontroller.kubeplus)
E0424 11:08:58.648548   44329 reflector.go:205] github.com/cloud-ark/kubeplus/postgres-crd/pkg/client/informers/externalversions/factory.go:74: Failed to list *v1.Postgres: the server could not find the requested resource (get postgreses.postgrescontroller.kubeplus)
```

I'm using Minikube, Kube version 1.10.

**Comment by devdattakulkarni** [comment]
@chrisduong Please try postgres-crd-v2

I have made several updates to it today.
Let me know how it goes..

**Comment by chrisduong** [comment]
Still same error.

**Comment by devdattakulkarni** [comment]
Which command/step is giving the error?

Did you register the CRD? 

kubectl create -f artifacts/examples/crd.yaml

Did this work?

**Comment by chrisduong** [comment]
Yes, I missed that step. Just figured out this also. Thanks

But there is a bug complaining "cannot found psql command". It is the `psql tool` inside of the Pod. Not the host where I run the command (deploying custom controller?).

```
 DropUserCmds:[]
   AlterUserCmds:[]
   UserAndDBCmds:[create database moodle; create user devdatta with password 'pass123'; create user pallavi with password 'pass234';]
   SetupCmds:[\c moodle; create table moodle_data1 (items varchar(250)); insert into moodle_data1 (items) values ('moodle data1'); insert into moodle_data1 (items) values ('moodle data1'); insert into moodle_data1 (items) values ('moodle data2'); grant all privileges on table moodle_data1 to devdatta; grant all privileges on table moodle_data1 to pallavi;]
Creating deployment...
Created deployment "client25".
------------------------------
Creating service...
Created service "client25".
------------------------------
Waiting for Pod to get ready.

Waiting for Pod to get ready.

Waiting for Pod to get ready.
Waiting for Pod to get ready.
Waiting for Pod to get ready.
Waiting for Pod to get ready.
About to create temp db file for user and db commandsDatabase setup file:/tmp/setup-db
Now setting up the database
Database setup command: [psql -h 192.168.99.100 -p 31498 -U postgres -f /tmp/setup-db]
Err:exec: "psql": executable file not found in $PATH
Out:[]
Out:
CRD client25 created
Check using: kubectl describe postgres client25
E0424 20:31:56.779250    9009 runtime.go:66] Observed a panic: &exec.Error{Name:"psql", Err:(*errors.errorString)(0xc4200c0200)} (exec: "psql": executable file not found in $PATH)
/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:573
/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:502
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:742
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:691
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:303
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:237
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:245
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:198
/Users/cduong13/go/src/github.com/cloud-ark/kubeplus/postgres-crd-v2/controller.go:184
/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.10.1/libexec/src/runtime/asm_amd64.s:2361
panic: exec: "psql": executable file not found in $PATH [recovered]
	panic: exec: "psql": executable file not found in $PATH

goroutine 83 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/cduong13/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1c7f200, 0xc4205560c0)
	/usr/local/Cellar/go/1.10.1/libexec/src/runtime/panic.go:502 +0x229
main.setupDatabase(0x1de8965, 0xe, 0xc4203c89d0, 0x5, 0xc4204b2080)
	/Users/cduong13/go/src/gith
```

**Comment by devdattakulkarni** [comment]
Cool!

So the psql tool needs to be installed on the Host/Minikube VM -- The controller code, which is running on the  Host, will use it to remotely perform actions against the Service IP.

Did you do this step:
"
Install Postgres client:
brew install postgresql
sudo apt-get install postgresql-client
"

**Comment by devdattakulkarni** [comment]
@chrisduong https://join.slack.com/t/cloudark/shared_invite/enQtMjMyMjYwMTAzODMwLWM2ZjY1Yjc0MTFhZjZjODk4ZTZjODAwZWE2ZWE2Mzg0MjMxNzQ3NzUxNDlkMDg1OGNmYzU0NTRiNDBkNGI0ODM

**Comment by chrisduong** [comment]
Thanks @devdattakulkarni . It worked.

**Comment by devdattakulkarni** [comment]
@chrisduong Glad to know that the operator worked for you :smiley:

**Comment by devdattakulkarni** [comment]
@chrisduong Hi!
We are starting KubePlus community meetings next week. They will be on Tuesdays at 10.30 a.m. US Central time. The meetings will be on #kubeplus Slack channel in the CNCF workspace. I hope you are able to join us for these meetings as we look forward to building KubePlus further with community inputs and involvement.
