### ISSUE TITLE
Interface conversion error

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#1366]
2024/11/12 20:02:34 http: panic serving 10.0.1.95:52398: interface conversion: interface {} is nil, not *v1.AdmissionReview
goroutine 7324687 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x1482a40, 0xc0017499e0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
main.getFieldValueFromInstance({0xc000b50c90?, 0xc000012018?}, {0xc0005bcd9e, 0xd}, {0xc0015004be, 0x4})
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:940 +0x35a
main.applyPolicies(0xc001229620?, {0xc001229620, 0x2b}, {0xc0005bcd9e, 0xd}, {0xc0015004be, 0x4}, {0xc0003d2620?, 0x18048e0?})
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:912 +0xd08
main.(*WebhookServer).mutate(0x18051a0?, 0xc001401380, {0xc0014e2790, 0x6})
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:278 +0xb25
main.(*WebhookServer).serve(0xc0004f3ae0?, {0x1816c20, 0xc00073e000}, 0xc000033700)
	/home/vagrant/go/src/github.com/cloud-ark/kubeplus/mutating-webhook/webhook.go:1784 +0x45d
net/http.HandlerFunc.ServeHTTP(0xc00073e000?, {0x1816c20?, 0xc00073e000?}, 0x1613a38?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc001362aed?, {0x1816c20, 0xc00073e000}, 0xc000033700)
	/usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x180a7a0?}, {0x1816c20, 0xc00073e000}, 0xc000033700)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000490d80, {0x1817358, 0xc000614180})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
2024/11/12 20:02:34 http: panic serving 10.0.1.95:52392: interface conversion: interface {} is nil, not *v1.AdmissionReview

**Comment by devdattakulkarni** [comment]
KubePlus chart version: kubeplus-chart-3.0.44
