### ISSUE TITLE
Certificate validation issue when running behind a firewall/proxy

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#182]
The machine on which this test was run included a firewall software running on it in the background. KubePlus seems to get into certificate validation issue in such a setup. Turning off the firewall caused this issue to go away and then KubePlus deployments worked.

kubectl logs kubeplus-gzzs7 -c operator-deployer
Created tunnel using local port: 36251
Effective Operators to install:[https://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true]
Error: rpc error: code = Unknown desc = configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system"Installing chart.
Chart URLhttps://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true
ValuesString:null
ChartValues:[]
Name:https://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true, Version:
Filename:
Name:https://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true
panic: Get https://github.com/cloud-ark/operatorcharts/blob/master/postgres-crd-v2-chart-0.0.2.tgz?raw=true: x509: certificate signed by unknown authority

goroutine 1 [running]:
main.locateChartPath(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4208b8060, 0x60, 0x0, 0x0, ...)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus/operator-deployer/install.go:494 +0xe55
main.installChart(0x18cfd20, 0xc420692240, 0x18a0ee0, 0xc42009c008, 0xc4208b8060, 0x60, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus/operator-deployer/install.go:176 +0x1cc
main.main()
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus/operator-deployer/helm.go:220 +0x11b5

**Comment by devdattakulkarni** [comment]
operator-deployer is no longer used, so closing this issue.

If we see this happen with helm then we should create a new issue.
