### ISSUE TITLE
Mysql client gives runtime error for mysql-operator: nil pointer dereference

### ISSUE THREAD

**Issue by danielpygo** [cloud-ark/kubeplus#201]
When trying to follow examples/mysql/steps.txt, it is failing on the last step. mysql client image will not run correctly and I get the stack trace seen below. 

$ kubectl version
Client Version: v1.10.0
Server Version: v1.10.0

$ helm version
Client v2.12.3
Server: v2.12.3

$ minikube version
minikube version: v0.28.2

OS:
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

```
$ kubectl run mysql-client --image=mysql:5.7 -it --rm --restart=Never -- mysql -h mysql -uroot -p7wHjU9VXKVDR2FOB -e 'SELECT 1'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x200de4e]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd.RunRun(0x2f45f80, 0xc4207be660, 0x2f1b080, 0xc42009a000, 0x2f1b0c0, 0xc42009a008, 0x2f1b0c0, 0xc42009a010, 0xc420230f00, 0xc4206ceea0, ...)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:328 +0x10ae
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRun.func1(0xc420230f00, 0xc4206ceea0, 0x8, 0xd)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:105 +0x144
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420230f00, 0xc4206ceb60, 0xd, 0xd, 0xc420230f00, 0xc4206ceb60)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420146780, 0xc420845ed8, 0xc420845ee0, 0x12a05f200)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420146780, 0x24c9d78, 0x30e55e0)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```

**Comment by devdattakulkarni** [comment]
Seems like an issue related to your environment. I haven't seen it in my setup.

**Comment by danielpygo** [comment]
Okay
