### ISSUE TITLE
Error when creating png connections output in Vagrant VM

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#898]
```
vagrant@vagrant:~$ kubectl connections HelloWorldService hs1 $HELLOWORLD_NS -o png
Traceback (most recent call last):
  File "/src/connections.py", line 101, in <module>
    graph.draw(connections_json, output_folder, relsToHide)
  File "/src/connections.py", line 16, in draw
    fp = open(output_folder + "/" + connections_json, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/root//connections-op.json'
Output available in: /home/vagrant/plugins/connections-op.json.gv.png
```

**Comment by devdattakulkarni** [comment]
Note that in the png output is actually generated.
